language: cpp
compiler:
  - gcc
  - clang

os:
  - linux
  - osx

git:
  depth: 1

dist: trusty
sudo: required

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update

install:
  - mkdir -p ../build
  - cd ../build
  - cmake -DCMAKE_BUILD_TYPE=Release $TRAVIS_BUILD_DIR
  - cmake --build . --config Release
  - ctest
