language: cpp
compiler:
  - gcc
  - clang

os:
  - linux
  - osx

git:
  depth: 1

dist: trusty
sudo: required

before_install:
  - if [ `uname` = "Linux" ]; then
      sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa ;
      sudo add-apt-repository -y ppa:josh-bialkowski/cmake ;
      sudo apt-get update ;
      sudo apt-get install -y --force-yes cmake zlib1g-dev ;
    fi

install:
  - mkdir -p ../build
  - cd ../build
  - cmake -DCMAKE_BUILD_TYPE=Release $TRAVIS_BUILD_DIR
  - cmake --build . --config Release
  - ctest
